class Question
  attr_reader :numOne, :numTwo, :answer
  # generated by THE GAME
  # two random numbers between 1 to 20
  # it has the answer (the sum of the numbers)

  def initialize
    @numOne = 1 + rand(20)
    @numTwo = 1 + rand(20)
    @answer = @numOne + @numTwo
  end
end